### ISSUE TITLE
Start API work?

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/DeviceSwap#1]
**Problem description**
Hello @ShutingQing  @MarkusKuemmerle  @wwAMRA  - There is not activity on this project since its creation.

Perhaps I'm wrong but I tend to thing that 1/this API is useful and 2/should not be difficult to craft (as we can use pattern for our other API)

I'm volunteer to ignite some work here but also we can link this API to another project.

**Additional context**
Link to the API: https://github.com/camaraproject/WorkingGroups/blob/main/APIBacklog/documentation/SupportingDocuments/API%20proposals/Device%20Swap.md

**Comment by ShutingQing** [comment]
Hi @bigludo7 , I just noticed this. I'll kindly suggest to ask Waseem to proceed the progress. 

I just noticed that I'm the code owner. Actually this is wrong. (https://github.com/camaraproject/WorkingGroups/blob/main/APIBacklog/documentation/SupportingDocuments/API%20proposals/Device%20Swap.md) I have removed my name here. 

For this API, I think it's valuable. For example in China, we may apply 5 sim cards in one operator. We have 3 main operators, so we may own 15 sim cards. For some scenario, someone will buy or sell spare sim cards illegally. Usages are like, for e-markets, merchant who have a online store, will use different sim cards with different accounts to do some fake orders and comments. Device Swap can be useful for OTTs to filter these factors in rating. 

So i'll suggest anyone who have interest to volunteer to contribute in this API.

**Comment by StefanoFalsetto-CKHIOD** [comment]
Hi All, is there some scheduled call to start talking about this service? I would like to contribute to this project.

**Comment by bigludo7** [comment]
HI @StefanoFalsetto-CKHIOD 
Not yet but are currently looking for Maintainers, Codeowners, and Contributors to ignite some work soon. Have you registered to the Device Swap CAMARA project ?

**Comment by StefanoFalsetto-CKHIOD** [comment]
Hi @bigludo7 I confirm my interest as Contributor. If interested, I can share the vision of Hutchison use of device related attributes.

**Comment by bigludo7** [comment]
As we have our first meeting (documented [here](https://wiki.camaraproject.org/display/CAM/2024-07-23+Device+Swap+Minutes)) I can close this one.
