### ISSUE TITLE
Include Device Swap description

### ISSUE THREAD

**Issue by jgarciahospital** [camaraproject/DeviceSwap#16]
Proposal to include in API description, avoiding explicit Multi-SIM additional discussion (only including it as new device IMEI is associated to same MSISDN). We can later follow the discussion on considering only new multiSIM devices or consider any change.

**Device swap**: A Device Swap is a process in which a user's mobile phone number (MSISDN) is associated with a new device (IMEI).

This typically occurs when the user switches to a new mobile device, either by upgrading, replacing a lost or damaged device, or other similar reasons. A Device Swap also happens during actions like activating a new device associated with the same phone number, also known as multiSIM. New Device activation is considered as a Device Swap as well, as the phone number is associated with a device it was not associated before.

_Originally posted by @jgarciahospital in https://github.com/camaraproject/DeviceSwap/discussions/11#discussioncomment-10726846_

**Comment by StefanoFalsetto-CKHIOD** [comment]
I think it is almost OK, I have a little note regarding the _interpretation_ of this rule.

When we use the term "new" we are implicitly saying that there is some "old" thing somewhere around. But we know that this event is raised for old and for new devices. I mean, while from the technical point of view this description is fine, from the business point of view it could lead to some misinterpretation and could need some extra explanation (e.g., classic business question: is the device swap returning empty string when the SIM is put into an older phone? We all know the answer but business people not always.)

Hence maybe we can change it a bit stressing the concept around the association between MSISDN and IMEI and not around the device. I have no clear idea about it, but a new definition could be:

Device swap: A Device Swap is a process in which the association between a user's mobile phone number (MSISDN) and a device (IMEI) is created for the first time or changes for any reasons.

**Comment by jgarciahospital** [comment]
In order to simplify, I think that can be a good approach. I'll update the PR accordingly, thanks @StefanoFalsetto-CKHIOD
