### ISSUE TITLE
Update and review CODEOWNERS and MAINTAINERS.md file

### ISSUE THREAD

**Issue by hdamker** [camaraproject/DeviceSwap#3]
**Problem description**

Update CODEOWERNS and MAINTAINERS.md as per points 3 and 7 of https://github.com/camaraproject/Governance/issues/134
and ensure that all Maintainer and Codeowner are accepted the invite into the CAMARA GitHub organization.

**Expected action**

Create PR for the updates
Review the current Maintainer & Codeowner list

**Additional context**

The sub project has currently only one Maintainer (@ShutingQing) and one Codeowner. The Codeowner (@wwAMRA) hasn't accepted the invite to the CAMARA GitHub organization yet.

**Comment by bigludo7** [comment]
Hello
Up on this one as we have a first call July23th 

I'm volunteer for Orange to contribute

@rartych  @StefanoFalsetto-CKHIOD @jgarciahospital looking for your support.

cc: @hdamker

**Comment by bigludo7** [comment]
+ @ShutingQing & @wwAMRA

**Comment by bigludo7** [comment]
For Orange @bigludo7 as CodeOwner & Maintainer

**Comment by krishvenkatachalam** [comment]
For MTN @krishvenkatachalam  as code owner and @sanj14oct  , @KarishmaTayal as Maintainer

**Comment by hdamker** [comment]
As @ShutingQing has merged #9 early, the MAINTAINER.md file is currently inconsistent with @camaraproject/device-swap_maintainers, as the invitation @sanjayoct14 hasn't been accepted yet. 

**Expected action:**
@sanjayoct14 accepts the invitation from GitHub to the CAMARA organization

**Alternative:**
The MAINTAINER.md file get's adapted.

**Comment by bigludo7** [comment]
@hdamker  We're good now with @sanjayoct14 right?

i will keep this issue open one more week if any volunteer to join.

**Comment by hdamker** [comment]
> We're good now with @sanjayoct14 right?

@bigludo7 yes.

**Comment by jgarciahospital** [comment]
Hi @bigludo7 , confirming myself as maintainer

**Comment by bigludo7** [comment]
Completed by #8 #9 and #12
